rootProject.name = "jml-tools"
include("prettyprinting")
include("lint")
include("smt")
include("wd")
include("jml2java")
include("stat")
include("redux")
include("utils")
include("xpath")
include("cli")
include("lsp")
include("web")
